### PR TITLE
Docker protocol docs

### PR DESCRIPTION
**Pull request by cainj13**
KEYCLOAK-3592

### CODE REVIEW

**Comment by stianst** [comment]
DON'T MERGE UNTIL 3.x

**Comment by stianst** [comment]
Docs where moved to https://github.com/keycloak/keycloak-documentation. Could you send PR there please?

**Comment by cainj13** [comment]
Sure thing, see #55: https://github.com/keycloak/keycloak-documentation/pull/55

**Comment by stianst** [comment]
Thanks - closing this

**Pull request closed without merging**
